# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 12:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190311_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsdata',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 11, 12, 31, 30, 801119)),
        ),
    ]
