# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 12:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190311_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsdata',
            name='created_at',
            field=models.CharField(max_length=30, verbose_name=datetime.datetime(2019, 3, 11, 12, 35, 39, 303554)),
        ),
    ]
