# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20190311_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsdata',
            name='created_at',
        ),
        migrations.AddField(
            model_name='jobsdata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
