# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 12:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20190311_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsdata',
            name='created',
            field=models.CharField(default=datetime.datetime(2019, 3, 11, 12, 46, 2, 265592), max_length=30),
        ),
    ]
